version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app

  unit-test-web:
    build:
      context: .
      dockerfile: ${DOCKERFILE_NAME}
    volumes:
      - ./:/usr/src/app
    command: ['yarn', 'test:watch']
