version: '3.9'
services:
  web:
    image: dragmove/tmpl-next-ssg:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./:/usr/src/app
