version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app

  # unit-test-web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./:/usr/src/app
  #   command: ['yarn', 'test:watch']
