name: ✅ Unit Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'develop'
      - 'epic/*'
    paths:
      - '**/*.tsx?'

jobs:
  unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository codes
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
          yarn --version
      - name: Check dependencies
        run: yarn install --immutable
      - name: Run Test
        run: yarn test
      - name: Print Test Coverage
        run: yarn test:coverage
